- hosts : mongo-demo
  tasks :
  - name: install mongoDB 
    sudo: yes
    apt: 
      name: mongodb
      state: present
      update_cache: yes

  - name: copy config file
    copy:
      src: mongodb.conf
      dest: /etc/mongodb.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart mongodb
 
  - name: create /etc/security/limits.d/mongodb.conf
    copy:
      src: security-mongodb.conf
      dest: /etc/security/limits.d/mongodb.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart mongodb

  - name: Ensure mongodb is running and and enabled to start automatically on reboots
    systemd:
      name: mongodb
      enabled: yes
      state: started